### PR TITLE
hacktoberfest2022

### PR DESCRIPTION
**Pull request by raj-hero**
Created cpp file for all the 3 tree traversals, also includes the insert operation.
@vashuteotia123 Do add the "hacktoberfest-accepted" tag if no issues are found. Mention the issues if found any

### CODE REVIEW

**Comment by raj-hero** [comment]
@vashuteotia123  Do add the "hacktoberfest-accepted" tag if no issues are found. Mention the issues if found any

**Comment by raj-hero** [comment]
@vashuteotia123 Do add the "hacktoberfest-accepted" tag if no issues are found. Mention the issues if found any

**Comment by raj-hero** [comment]
pull request #159 for issues #182 #183 #184  - all 3 in one file @vashuteotia123

**Review by vashuteotia123 — APPROVED** [review]
Looks good.

**Pull request merged**
