### PR TITLE
This pr solves issue #4

### PR DESCRIPTION
**Pull request by saimaheshtaduri**
Breadth First Search algorithm is added in C++

### CODE REVIEW

**Comment by saimaheshtaduri** [comment]
@vashuteotia123  please review the code abd let me know if you need any changes.
Thanks :)

**Review by vashuteotia123 — CHANGES_REQUESTED** [review]
Update the directory from "searching" to "Searching".

**Comment by saimaheshtaduri** [comment]
@vashuteotia123 done.
please review it now. Thanks :)

**Review by vashuteotia123 — APPROVED** [review]
Looks good.

**Pull request merged**
