### PR TITLE
this pr solves issue #21

### PR DESCRIPTION
**Pull request by saimaheshtaduri**
added dijkstra's algorithm in C++

### CODE REVIEW

**Review by vashuteotia123 — COMMENTED** [review]
Update the directory from "graphs" to "Graphs".

**Comment by saimaheshtaduri** [comment]
@vashuteotia123  done.
Please review it now. Thanks :)

**Review by vashuteotia123 — APPROVED** [review]
Looks good.

**Comment by saimaheshtaduri** [comment]
@vashuteotia123  can you add hacktoberfest-accepted label ?

**Pull request merged**
